version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: app
    ports:
      - "9999:8000"
    depends_on:
      - db
