"""“commit”

Revision ID: 886671d2dba7
Revises: fc89c6742f1f
Create Date: 2024-06-14 16:21:16.627705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886671d2dba7'
down_revision: Union[str, None] = 'fc89c6742f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('registered_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    op.execute("""
    INSERT INTO role (id, name, permissions)
    SELECT id, name, permissions::json FROM (
        SELECT 1 as id, 'user' as name, '{"read": true, "write": false, "delete": false}' as permissions
        UNION ALL
        SELECT 2 as id, 'admin' as name, '{"read": true, "write": true, "delete": false}' as permissions
        UNION ALL
        SELECT 3 as id, 'root' as name, '{"read": true, "write": true, "delete": true}' as permissions
    ) as subquery
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'registered_at')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
